inherits: configs/kaggle_encoder_only_5epoch_experiment_judge_groq.yaml

llm_judge:
  input_path: /kaggle/working/reports/eat_bart_encoder_only_alpha_0_1_differential_lr_early_stop_experiment_generations.csv
  output_path: /kaggle/working/reports/eat_bart_encoder_only_alpha_0_1_differential_lr_early_stop_experiment_llm_judge_groq.csv
  summary_output_path: /kaggle/working/reports/eat_bart_encoder_only_alpha_0_1_differential_lr_early_stop_experiment_llm_judge_groq_summary.csv
